exec --no-startup-id bash -c 'tmux kill-session -t firewall_boot_script; sleep 1; tmux new-session -d -s firewall_script "$HOME/scripts/firewall-boot-status.sh"'

exec --no-startup-id dex --autostart --environment i3

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
#exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock -c 000000 --nofork

exec_always --no-startup-id ~/scripts/i3-dynamic-borders.py

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
#exec_always --no-startup-id /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 
exec_always --no-startup-id lxpolkit
exec_always --no-startup-id nm-applet
exec_always --no-startup-id numlockx on
exec_always --no-startup-id volumeicon
exec_always --no-startup-id copyq
exec_always --no-startup-id xset s off
exec_always --no-startup-id xset -dpms
exec_always --no-startup-id xset s noblank
exec_always --no-startup-id xfce4-power-manager
##enable this for brightness keys function
#exec always --no-startup-id xfsettingsd
exec_always --no-startup-id dunst -config ~/.config/dunst/dunstrc
exec --no-startup-id bash ~/scripts/dual.sh
#exec --no-startup-id bash -c "sleep 1 && ~/scripts/nordconnect.sh"


#autostart
#exec --no-startup-id sh .config/i3/autostart.sh

